---
# tasks file for apache-simple

- name: install httpd package
  yum: 
   name: "{{ item }}"
   state: present
  loop: "{{ httpd_packages }}"
  notify: restart apache service

- name: copy index.htmp
  template:
     src: index.html.j2
     dest: /var/www/html/index.html

- name: start httpd
  service: 
    name: httpd
    state: started
    enabled: yes 
